language: node_js
node_js:
- 6
notifications:
  slack:
    secure: d6xalLh+bzGsBi1eOQyr0NTnNYEC/iDzAJOBGSO8AgI3RoPlJw3cFq35st7xybKPgpqxYHwOW5ovSFhJ2uFCUiO7WRclTiiQck5ve4iEwly1hJknszMOKCApaxBuhcruwPVGBhzxHvTtPtnsJ0s8zz1YRh2q6rUPWJo0i2eKgce7S3BEcM6uTvI6mVumO0UZb2c7Du409QxcY3l4hqRbIj9FpJf0Lxlbkkk/lOYlnvjs/3EUQvp1LxtSfRN+iw/l2wPUWjjARK75AyrjoPMjGKme5qzQkFGQMmwmgSi9pkDNtM1uf7SrwPgaun8OFo0aXGJ4b8yi/UP+qSQiMaH2yJch7AwCohQvioEcxJKh1Og8AgkWWLhWwM71uDIhkIInLq+60VdEJCl0TGCLiebZe64YqMjrPsd6OegTCgaokeK+sCDd5wj9CyDVvouS9GCF5pZGwgJ/OICbXKDDfJgrBq2BS/t2p8ptr4e0nn7c7aiDlvUs8tZjaJqo40n6lM8FTXl6PxPxntqjRrIFz2SLVZQ7DXSmJKUQmzYw1nxWjz45iElw0YNDEBFJOQBg4x7YwT5Mi5YvfYE/T4SpO5gwv/r7VC3/OG5oFyKebJf5GJvdDfKksXym/EJUcN0jWDu/swze5G0lZcAllPaCNmR0Hpmkyks8nNZMgPQ35dWhnI0=
